name: Deploy

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Accept SSH host key
      run: |
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts
        chmod 600 ~/.ssh/known_hosts
      
    - name: Execute remote commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSHKEY }}
        script: |
          cd /var/www/yu-link
          git fetch origin deploy
          git reset --hard origin/deploy
          sudo chown -R ${{ secrets.USERNAME }}:${{ secrets.USERNAME }} .
          sudo chown -R www-data:www-data ./storage
          sudo chown -R www-data:www-data ./bootstrap/cache
          composer install --optimize-autoloader --no-dev
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
